import { RetouchPreset, DEFAULT_RETOUCH_OPTIONS } from '../types';

export const BUILT_IN_PRESETS: RetouchPreset[] = [
  {
    id: 'builtin-neutral',
    name: 'Neutre',
    isBuiltIn: true,
    createdAt: '2024-01-01T00:00:00.000Z',
    options: { ...DEFAULT_RETOUCH_OPTIONS },
  },
  {
    id: 'builtin-portrait',
    name: 'Portrait',
    isBuiltIn: true,
    createdAt: '2024-01-01T00:00:00.000Z',
    options: {
      ...DEFAULT_RETOUCH_OPTIONS,
      temperature: 8,
      exposure: 5,
      contrast: -10,
      highlights: -20,
      shadows: 15,
      clarity: 10,
      texture: 8,
      sharpness: 20,
      vibrance: 15,
      saturation: 5,
    },
  },
  {
    id: 'builtin-paysage',
    name: 'Paysage',
    isBuiltIn: true,
    createdAt: '2024-01-01T00:00:00.000Z',
    options: {
      ...DEFAULT_RETOUCH_OPTIONS,
      contrast: 10,
      highlights: -15,
      shadows: 20,
      whites: 10,
      clarity: 25,
      dehaze: 20,
      vibrance: 20,
      saturation: 10,
      sharpness: 30,
    },
  },
  {
    id: 'builtin-sunset',
    name: 'Coucher de soleil',
    isBuiltIn: true,
    createdAt: '2024-01-01T00:00:00.000Z',
    options: {
      ...DEFAULT_RETOUCH_OPTIONS,
      temperature: 30,
      tint: 5,
      exposure: -5,
      contrast: 15,
      highlights: -30,
      shadows: 20,
      clarity: 15,
      vibrance: 30,
      saturation: 20,
    },
  },
  {
    id: 'builtin-bw',
    name: 'Noir & Blanc',
    isBuiltIn: true,
    createdAt: '2024-01-01T00:00:00.000Z',
    options: {
      ...DEFAULT_RETOUCH_OPTIONS,
      saturation: -100,
      vibrance: -100,
      contrast: 20,
      clarity: 30,
      sharpness: 25,
    },
  },
  {
    id: 'builtin-fade',
    name: 'Fade / Mat',
    isBuiltIn: true,
    createdAt: '2024-01-01T00:00:00.000Z',
    options: {
      ...DEFAULT_RETOUCH_OPTIONS,
      contrast: -25,
      highlights: -20,
      shadows: 30,
      blacks: 20,
      vibrance: -15,
      saturation: -10,
    },
  },
  {
    id: 'builtin-vivid',
    name: 'Éclatant',
    isBuiltIn: true,
    createdAt: '2024-01-01T00:00:00.000Z',
    options: {
      ...DEFAULT_RETOUCH_OPTIONS,
      exposure: 5,
      contrast: 20,
      clarity: 20,
      dehaze: 10,
      vibrance: 35,
      saturation: 20,
      sharpness: 25,
    },
  },
];
